/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#0b1c30",
        "tertiary": "#000000",
        "border-hairline": "#E2E8F0",
        "inverse-primary": "#bec6e0",
        "on-primary-container": "#7c839b",
        "surface-dim": "#cbdbf5",
        "surface-tint": "#565e74",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#7ffc97",
        "surface-container": "#e5eeff",
        "deal-orange": "#EA580C",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#007230",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-container": "#00174b",
        "on-error": "#ffffff",
        "badge-emerald-tint": "#DCFCE7",
        "on-tertiary-fixed": "#00174b",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed-variant": "#003ea8",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed-variant": "#005320",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "on-primary-fixed-variant": "#3f465c",
        "badge-blue-tint": "#DBEAFE",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "secondary": "#006e2d",
        "tertiary-fixed": "#dbe1ff",
        "surface-container-high": "#dce9ff",
        "on-surface-variant": "#45464d",
        "secondary-container": "#7cf994",
        "secondary-fixed-dim": "#62df7d",
        "surface-subtle": "#F8FAFC",
        "on-tertiary": "#ffffff",
        "primary": "#000000",
        "on-secondary-fixed": "#002109",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#bec6e0",
        "surface-variant": "#d3e4fe",
        "primary-container": "#131b2e",
        "background": "#f8f9ff",
        "on-tertiary-container": "#497cff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.75rem",
        margin: "2rem",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "Poppins", "sans-serif"],
        "body-lg": ["Inter", "Poppins", "sans-serif"],
        "body-md": ["Inter", "Poppins", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "Poppins", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "Poppins", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "Poppins", "sans-serif"],
        "body-sm": ["Inter", "Poppins", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Poppins", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Poppins", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
